Adding the umbrella chart for amazon
SUSE-Enceladus/csp-rancher-usage-operator pull request #11
Opened 2023-08-01 19:31 UTC by chajain

2023-08-01 20:05 UTC, mbelur commented
Should we default to using the rancher version to 2.7.5 instead of 2.7.4 as the changes to support payg offering is in 2.7.5?

2023-08-01 20:29 UTC, guangyee commented on charts/umbrella/amazon/Chart.lock
> +  version: 2.7.5
May want to make the imageTag to 2.7.5 to be consistent

2023-08-01 20:36 UTC, guangyee commented on charts/umbrella/amazon/values.yaml
> +  bootstrapPassword: "rancher"
I think the bootstrapPassword is randomly generated if absent. Setting a default one will be problematic from security standpoint.

2023-08-01 20:37 UTC, guangyee commented on charts/umbrella/amazon/values.yaml
> +  replicas: 3
shouldn't replicas be default to 1?

2023-08-01 20:37 UTC, guangyee commented on charts/csp-rancher-usage-operator/100.0.0+up0.1.0/values.yaml
> +rancherImageTag: v2.7.4
v2.7.5?

2023-08-01 20:38 UTC, guangyee requested changes
Also, should we be using aws instead amazon? Though I don't have a strong opinion on this one.

2023-10-27 19:03 UTC, chajain commented
Decide to go with deployer option

2023-10-27 19:03 UTC, closed without merging